[package]
name = "drive-optimization-wizard"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17.9"
tokio = { version = "1.0", features = ["full"] }
inquire = "0.7.5"

[[bin]]
name = "dow"
path = "src/main.rs"